export { default as LessonPage } from "./lessonPage/LessonPage";
export { default as DictionaryPage } from "./dictionaryPage/DictionaryPage";
export { default as GrammarPage } from "./grammarPage/GrammarPage";
export { default as GrammarDetailsPage } from "./grammarDetailsPage/GrammarDetailsPage";
export { default as UserInfoPage } from "./userInfoPage/UserInfoPage";
export { default as RegisterPage } from "./registerPage/RegisterPage";
export { default as StatisticsPage } from "./statisticsPage/StatisticsPage";
export { default as LoginPage } from "./loginPage/LoginPage";
export { default as MainPage } from "./mainPage/MainPage";
